--************************************** [REINOS]
/*
TODO:
Arreglar meses
*/
INSERT ALL
INTO REINOS (NOMBRE, MES, LOGOTIPO) VALUES 
('Tauro','May',
'
     Tauro
    .     .
    ''.___.''
    .''   `.    
   :       :   
   :       :
    `.___.'' 
')
INTO REINOS (NOMBRE, MES, LOGOTIPO) VALUES 
('Aries','JAN',
'
     Aries
   .-.   .-.
  (_  \ /  _)
       |
       |
')
INTO REINOS (NOMBRE, MES, LOGOTIPO) VALUES 
('Geminis','JUN',
'
    Geminis
    ._____.
      | |
      | |
     _|_|_
    ''     ''
')
INTO REINOS (NOMBRE, MES, LOGOTIPO) VALUES 
('Cancer','JUN',
'
     Cancer
      .--.
     /   _`.
    (_) ( )
   ''.    /
     `--''
')
INTO REINOS (NOMBRE, MES, LOGOTIPO) VALUES 
('Leo','JUN',
'
      Leo
      .--.
     (    )
    (_)  /
        (_,
')
INTO REINOS (NOMBRE, MES, LOGOTIPO) VALUES 
('Virgo','JUN',
'
       Virgo
 _
  '' `:--.--.
     |  |  |_
     |  |  | )
     |  |  |/
          (J
')
INTO REINOS (NOMBRE, MES, LOGOTIPO) VALUES 
('Libra','JUN',
'
       Libra
        __
   ___.''  ''.___
   ____________
')
INTO REINOS (NOMBRE, MES, LOGOTIPO) VALUES 
('Escorpio','JUN',
'
     Escorpio
   _
  '' `:--.--.
     |  |  |
     |  |  |
     |  |  |  ..,
           `---'':
')
INTO REINOS (NOMBRE, MES, LOGOTIPO) VALUES 
('Sagitario','JUN',
'
    Sagitario
          ...
          .'':
        .''
    `..''
    .''`.
')
INTO REINOS (NOMBRE, MES, LOGOTIPO) VALUES 
('Capricornio','JUN',
'
    Capricornio
            _
    \      /_)
     \    /`.
      \  /   ;
       \/ __.''
')
INTO REINOS (NOMBRE, MES, LOGOTIPO) VALUES 
('Acuario','JUN',
'
     Acuario
 .-"-._.-"-._.-
 .-"-._.-"-._.-
')

INTO REINOS (NOMBRE, MES, LOGOTIPO) VALUES 
('Piscis','JUN',
'
       Piscis
     `-.    .-''
        :  :
      --:--:--
        :  :
     .-''    `-. 
')

SELECT * FROM DUAL;


DECLARE
    
    ORO CONSTANT CHAR(3):= 'ORO';
    HIERRO CONSTANT CHAR(6):= 'HIERRO';
    MADERA CONSTANT CHAR(6):= 'MADERA';
    
    CANT_INI_ORO_RESERVA CONSTANT NUMBER := 5000000;
    CANT_INI_HIERRO_RESERVA CONSTANT NUMBER := 2000000; 
    CANT_INI_MADERA_RESERVA CONSTANT NUMBER := 2000000; 
    CANT_INI_ORO_POR_REINO CONSTANT NUMBER := 40000; 
    CANT_INI_HIERRO_POR_REINO CONSTANT NUMBER := 10000; 
    CANT_INI_MADERA_POR_REINO CONSTANT NUMBER := 20000;
    VALOR_EN_ORO_MADERA CONSTANT NUMBER := 2;
    VALOR_EN_ORO_HIERRO CONSTANT NUMBER := 4;
    
    TIPO_TROPA_ATQ CONSTANT CHAR(3) := 'ATQ';
    TIPO_TROPA_DEF CONSTANT CHAR(3) := 'DEF';
    
    ARQUERA CONSTANT CHAR(7) := 'ARQUERA';
    PIQUERO CONSTANT CHAR(7) := 'PIQUERO';
    CABALLERO CONSTANT CHAR(9) := 'CABALLERO';
    MAGO CONSTANT CHAR(4) := 'MAGO';
    CANON CONSTANT CHAR(6) := 'CAÑON';
    TORRE CONSTANT CHAR(5) := 'TORRE';
    
    CANT_CORONAS_ARQ CONSTANT NUMBER := 2;
    CANT_CORONAS_PIQ CONSTANT NUMBER := 3;
    CANT_CORONAS_CAB CONSTANT NUMBER := 5;
    CANT_CORONAS_MAG CONSTANT NUMBER := 1;
    CANT_CORONAS_CAN CONSTANT NUMBER := 20;
    CANT_CORONAS_TOR CONSTANT NUMBER := 15;
    
    CANT_PUNTOS_ARQ CONSTANT NUMBER := 20;
    CANT_PUNTOS_PIQ CONSTANT NUMBER := 30;
    CANT_PUNTOS_CAB CONSTANT NUMBER := 50;
    CANT_PUNTOS_MAG CONSTANT NUMBER := 40;
    CANT_PUNTOS_CAN CONSTANT NUMBER := 450;
    CANT_PUNTOS_TOR CONSTANT NUMBER := 650;
    
    CANT_ORO_ARQ CONSTANT NUMBER := 20;
    CANT_ORO_PIQ CONSTANT NUMBER := 25;
    CANT_ORO_CAB CONSTANT NUMBER := 100;
    CANT_ORO_MAG CONSTANT NUMBER := 50;
    CANT_ORO_CAN CONSTANT NUMBER := 1000;
    CANT_ORO_TOR CONSTANT NUMBER := 2000;
    
    CANT_MADERA_ARQ CONSTANT NUMBER := 100;
    CANT_MADERA_PIQ CONSTANT NUMBER := 70;
    CANT_MADERA_CAB CONSTANT NUMBER := 20;
    CANT_MADERA_MAG CONSTANT NUMBER := 50;
    CANT_MADERA_CAN CONSTANT NUMBER := 500;
    CANT_MADERA_TOR CONSTANT NUMBER := 1000;

    CANT_HIERRO_ARQ CONSTANT NUMBER := 40;
    CANT_HIERRO_PIQ CONSTANT NUMBER := 60;
    CANT_HIERRO_CAB CONSTANT NUMBER := 30;
    CANT_HIERRO_MAG CONSTANT NUMBER := 50;
    CANT_HIERRO_CAN CONSTANT NUMBER := 2000;
    CANT_HIERRO_TOR CONSTANT NUMBER := 800;
    
    CANT_REINOS NUMBER;
    CURSOR CUR_REINOS IS SELECT NOMBRE FROM REINOS;
    TYPE TBL_REINOS IS TABLE OF REINOS%ROWTYPE;
    T_REINOS TBL_REINOS;
    
BEGIN
    SELECT COUNT(NOMBRE) INTO CANT_REINOS FROM REINOS;
    
    IF CANT_REINOS != 12 THEN
        DBMS_OUTPUT.PUT_LINE('La cantidad de reinos no es igual a 12, algo esta mal.');
    END IF;
    
    INSERT ALL
        INTO RECURSOS (NOMBRE, EXISTENCIA, RESERVA, VALOR, RESPALDO) VALUES (ORO, (CANT_INI_ORO_RESERVA + (CANT_INI_ORO_POR_REINO * CANT_REINOS)), CANT_INI_ORO_RESERVA, 1, NULL)
        INTO RECURSOS (NOMBRE, EXISTENCIA, RESERVA, VALOR, RESPALDO) VALUES (HIERRO, (CANT_INI_HIERRO_RESERVA + (CANT_INI_HIERRO_POR_REINO * CANT_REINOS)), CANT_INI_HIERRO_RESERVA, VALOR_EN_ORO_HIERRO , 'ORO')
        INTO RECURSOS (NOMBRE, EXISTENCIA, RESERVA, VALOR, RESPALDO) VALUES (MADERA, (CANT_INI_MADERA_RESERVA + (CANT_INI_MADERA_POR_REINO * CANT_REINOS)), CANT_INI_MADERA_RESERVA, VALOR_EN_ORO_MADERA , 'ORO')
        
        -- TAURO,ARIES,GEMINIS,CANCER,LEO,VIRGO,LIBRA,ESCORPIO,SAGITARIO,CAPRICORNIO,ACUARIO,PISCIS
        
        INTO TROPAS (NOMBRE, PUNTOS, CORONAS, TIPO) VALUES (ARQUERA, CANT_PUNTOS_ARQ,CANT_CORONAS_ARQ,TIPO_TROPA_ATQ)
        INTO TROPAS (NOMBRE, PUNTOS, CORONAS, TIPO) VALUES (PIQUERO, CANT_PUNTOS_PIQ,CANT_CORONAS_PIQ,TIPO_TROPA_ATQ)
        INTO TROPAS (NOMBRE, PUNTOS, CORONAS, TIPO) VALUES (CABALLERO, CANT_PUNTOS_CAB,CANT_CORONAS_CAB,TIPO_TROPA_ATQ)
        INTO TROPAS (NOMBRE, PUNTOS, CORONAS, TIPO) VALUES (MAGO, CANT_PUNTOS_MAG,CANT_CORONAS_MAG,TIPO_TROPA_ATQ)
        
        INTO TROPAS (NOMBRE, PUNTOS, CORONAS, TIPO) VALUES (CANON, CANT_PUNTOS_CAN,CANT_CORONAS_CAN,TIPO_TROPA_DEF)
        INTO TROPAS (NOMBRE, PUNTOS, CORONAS, TIPO) VALUES (TORRE, CANT_PUNTOS_TOR,CANT_CORONAS_TOR,TIPO_TROPA_DEF)
        
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(ARQUERA, ORO, CANT_ORO_ARQ)
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(ARQUERA, HIERRO, CANT_HIERRO_ARQ)
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(ARQUERA, MADERA, CANT_MADERA_ARQ)
        
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(PIQUERO, ORO, CANT_ORO_PIQ)
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(PIQUERO, HIERRO, CANT_HIERRO_PIQ)
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(PIQUERO, MADERA, CANT_MADERA_PIQ)
        
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(CABALLERO, ORO, CANT_ORO_CAB)
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(CABALLERO, HIERRO, CANT_HIERRO_CAB)
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(CABALLERO, MADERA, CANT_MADERA_CAB)
        
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(MAGO, ORO, CANT_ORO_MAG)
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(MAGO, HIERRO, CANT_HIERRO_MAG)
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(MAGO, MADERA, CANT_MADERA_MAG)
    
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(CANON, ORO, CANT_ORO_CAN)
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(CANON, HIERRO, CANT_HIERRO_CAN)
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(CANON, MADERA, CANT_MADERA_CAN)
        
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(TORRE, ORO, CANT_ORO_TOR)
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(TORRE, HIERRO, CANT_HIERRO_TOR)
        INTO VALORES_POR_TROPAS (NOMBRE_TROPA, NOMBRE_RECURSO,CANTIDAD) VALUES(TORRE, MADERA, CANT_MADERA_TOR)
    
    SELECT * FROM DUAL;

    FOR reino_regis IN CUR_REINOS LOOP
        INSERT ALL
            INTO TROPAS_POR_REINOS(NOMBRE_TROPA,NOMBRE_REINO,CANTIDAD) VALUES(ARQUERA, reino_regis.NOMBRE, 0)
            INTO TROPAS_POR_REINOS(NOMBRE_TROPA,NOMBRE_REINO,CANTIDAD) VALUES(PIQUERO, reino_regis.NOMBRE, 0)
            INTO TROPAS_POR_REINOS(NOMBRE_TROPA,NOMBRE_REINO,CANTIDAD) VALUES(CABALLERO, reino_regis.NOMBRE, 0)
            INTO TROPAS_POR_REINOS(NOMBRE_TROPA,NOMBRE_REINO,CANTIDAD) VALUES(MAGO, reino_regis.NOMBRE, 0)
            INTO TROPAS_POR_REINOS(NOMBRE_TROPA,NOMBRE_REINO,CANTIDAD) VALUES(CANON, reino_regis.NOMBRE, 0)
            INTO TROPAS_POR_REINOS(NOMBRE_TROPA,NOMBRE_REINO,CANTIDAD) VALUES(TORRE, reino_regis.NOMBRE, 0)
            
            INTO RECURSOS_POR_REINOS(NOMBRE_RECURSO,NOMBRE_REINO,CANTIDAD) VALUES(ORO, reino_regis.NOMBRE, CANT_INI_ORO_POR_REINO)
            INTO RECURSOS_POR_REINOS(NOMBRE_RECURSO,NOMBRE_REINO,CANTIDAD) VALUES(MADERA, reino_regis.NOMBRE, CANT_INI_MADERA_POR_REINO)
            INTO RECURSOS_POR_REINOS(NOMBRE_RECURSO,NOMBRE_REINO,CANTIDAD) VALUES(HIERRO, reino_regis.NOMBRE, CANT_INI_HIERRO_POR_REINO)
        SELECT * FROM DUAL;
    END LOOP;

END;
/

/*
SELECT * FROM RECURSOS;
SELECT * FROM TROPAS;
SELECT * FROM VALORES_POR_TROPAS;
SELECT * FROM RECURSOS_POR_REINOS;

*/
